version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "knowledge-base-api"
s3_bucket = "knowledge-base-deployment-artifacts"
s3_prefix = "knowledge-base"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []


[default.build]
[default.build.parameters]
cached = true
parallel = true
use_container = true

[default.sync]
[default.sync.parameters]
watch = true

[default.local_start_api]
[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda]
[default.local_start_lambda.parameters]
warm_containers = "EAGER"